Ext.Require("Scripts/Default.lua")
Ext.Require("Scripts/Keywords.lua")

Ext.Require("Scripts/ArtifactWeapons.lua")
Ext.Require("Scripts/ArtifactArmours.lua")
Ext.Require("Scripts/ArtifactJewelry.lua")

Ext.Require("Scripts/Abeyance.lua")
Ext.Require("Scripts/Benevolence.lua")
Ext.Require("Scripts/Celestial.lua")
Ext.Require("Scripts/Paucity.lua")
Ext.Require("Scripts/Predator.lua")
Ext.Require("Scripts/Purity.lua")
Ext.Require("Scripts/VS.lua")
Ext.Require("Scripts/Ward.lua")

Ext.Require("Scripts/CenturionDefiance.lua")
Ext.Require("Scripts/CenturionDodge.lua")
Ext.Require("Scripts/CelestialOffensive.lua")
Ext.Require("Scripts/Elementalist.lua")
Ext.Require("Scripts/Centurion.lua")
Ext.Require("Scripts/Occultist.lua")
Ext.Require("Scripts/Archers.lua")
Ext.Require("Scripts/Bomber.lua")
Ext.Require("Scripts/Brawlers.lua")
Ext.Require("Scripts/Healers.lua")
Ext.Require("Scripts/Paladin.lua")
Ext.Require("Scripts/Rogues.lua")
